### ISSUE TITLE
Chromecast is not working

### ISSUE THREAD

**Issue by BartoszJarocki** [kaltura/player-sdk-native-android#100]
Version used:  **v2.3.0.rc4**
Environment: **Nexus 5, Android 6.0.1**
Steps to reproduce: **just start player when chromecast is available**

Stacktrace:
`02-16 13:05:43.187 3941-3941/* I/chromium: [INFO:CONSOLE(7)] "setAttribute", source: https://cdnapisec.kaltura.com/html5/html5lib/v2.39/load.php?debug=false&lang=en&modules=acCheck%2CacPreview%2CairPlay%2Cbase64_decode%2Cbase64_encode%2Cchromecast%2Cclass%2CclosedCaptions%2CcontrolBarContainer%2CcurrentTimeLabel%2CdurationLabel%2CfullScreenBtn%2Cid3Tag%2Ckdark%2CkeyboardShortcuts%2ClargePlayBtn%2CliveAnalytics%2CliveStream%2CmatchMedia%2CmorePlugins%2CnativeBridge%2CplayPauseBtn%2Cplayerjs%2CqualitySettings%2CreportError%2Cscreenfull%2Cscrubber%2CsideBarContainer%2CsourceSelector%2CstatisticsPlugin%2Ctheme%2CtopBarContainer%2Cutf8_encode%2CvolumeControl%7Cjquery.client%2Ccolor%2Ccookie%2Cdebouncedresize%2ChoverIntent%2CmessageBox%2CmwEmbedUtil%2CmwExtension%2CnaturalSize%7Cjquery.ui.core%2Cmouse%2Cposition%2Cslider%2Ctooltip%2CtouchPunch%2Cwidget%7Cmediawiki.Uri%2CUtilitiesTime%2CUtilitiesUrl%2Cclient%2CjqueryMsg%2Ckmenu%2Clanguage%2Cutil%7Cmediawiki.util.tmpl%7Cmw.AkamaiMediaAnalytics%2CEmbedPlayer%2CEmbedPlayerImageOverlay%2CEmbedPlayerKplayer%2CEmbedPlayerNative%2CEmbedPlayerNativeComponent%2CEmbedTypes%2CKAnalytics%2CKBaseComponent%2CKBasePlugin%2CKBaseSmartContainer%2CKCuePoints%2CKDPMapping%2CKEntryLoader%2CKWidgetSupport%2CKalturaIframePlayerSetup%2CMediaElement%2CMediaPlayer%2CMediaPlayers%2CMediaSource%2CPlayerElement%2CPlayerElementFlash%2CPlayerElementHTML%2CPlayersJsReceiver%2CPluginManager%2CTextSource%2CajaxProxy%7Cmw.Language.names%7Cmw.MwEmbedSupport.style&pskwidgetpath=..%2Fkwidget-ps%2F&skin=no-theme&version=20160117T074201Z&* (7)
02-16 13:05:43.187 3941-3941/* I/chromium: [INFO:CONSOLE(7)] "chromecastAppId,FFCC6D19", source: https://cdnapisec.kaltura.com/html5/html5lib/v2.39/load.php?debug=false&lang=en&modules=acCheck%2CacPreview%2CairPlay%2Cbase64_decode%2Cbase64_encode%2Cchromecast%2Cclass%2CclosedCaptions%2CcontrolBarContainer%2CcurrentTimeLabel%2CdurationLabel%2CfullScreenBtn%2Cid3Tag%2Ckdark%2CkeyboardShortcuts%2ClargePlayBtn%2CliveAnalytics%2CliveStream%2CmatchMedia%2CmorePlugins%2CnativeBridge%2CplayPauseBtn%2Cplayerjs%2CqualitySettings%2CreportError%2Cscreenfull%2Cscrubber%2CsideBarContainer%2CsourceSelector%2CstatisticsPlugin%2Ctheme%2CtopBarContainer%2Cutf8_encode%2CvolumeControl%7Cjquery.client%2Ccolor%2Ccookie%2Cdebouncedresize%2ChoverIntent%2CmessageBox%2CmwEmbedUtil%2CmwExtension%2CnaturalSize%7Cjquery.ui.core%2Cmouse%2Cposition%2Cslider%2Ctooltip%2CtouchPunch%2Cwidget%7Cmediawiki.Uri%2CUtilitiesTime%2CUtilitiesUrl%2Cclient%2CjqueryMsg%2Ckmenu%2Clanguage%2Cutil%7Cmediawiki.util.tmpl%7Cmw.AkamaiMediaAnalytics%2CEmbedPlayer%2CEmbedPlayerImageOverlay%2CEmbedPlayerKplayer%2CEmbedPlayerNative%2CEmbedPlayerNativeComponent%2CEmbedTypes%2CKAnalytics%2CKBaseComponent%2CKBasePlugin%2CKBaseSmartContainer%2CKCuePoints%2CKDPMapping%2CKEntryLoader%2CKWidgetSupport%2CKalturaIframePlayerSetup%2CMediaElement%2CMediaPlayer%2CMediaPlayers%2CMediaSource%2CPlayerElement%2CPlayerElementFlash%2CPlayerElementHTML%2CPlayersJsReceiver%2CPluginManager%2CTextSource%2CajaxProxy%7Cmw.Language.names%7Cmw.MwEmbedSupport.style&pskwidgetpath=..%2Fkwidget-ps%2F&skin=no-theme&version=20160117T074201Z&* (7)
02-16 13:05:43.188 3941-3941/* D/KControlsView: shouldOverrideUrlLoading: js-frame:setAttribute:0:%5B%22chromecastAppId%22%2C%22FFCC6D19%22%5D
02-16 13:05:43.197 3941-3941/* E/KRouterManager: Error parsing json
                                                                         org.json.JSONException: Value FFCC6D19 of type java.lang.String cannot be converted to JSONArray
                                                                             at org.json.JSON.typeMismatch(JSON.java:111)
                                                                             at org.json.JSONArray.<init>(JSONArray.java:96)
                                                                             at org.json.JSONArray.<init>(JSONArray.java:108)
                                                                             at com.kaltura.playersdk.cast.KRouterManager.initialize(KRouterManager.java:66)
                                                                             at com.kaltura.playersdk.PlayerViewController.setAttribute(PlayerViewController.java:762)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.kaltura.playersdk.PlayerViewController.handleHtml5LibCall(PlayerViewController.java:587)
                                                                             at com.kaltura.playersdk.KControlsView$CustomWebViewClient.shouldOverrideUrlLoading(KControlsView.java:143)
                                                                             at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:325)
                                                                             at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:266)
                                                                             at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                             at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:37)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-16 13:05:43.197 3941-3941/* D/chromecast.initialize: FFCC6D19`

**Comment by kaltura-hooks** [comment]
Hi @BartoszJarocki,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by noamtamim** [comment]
Please test with v2.4.0.rc1 and MWE v2.40. 
When you write "just start the player", which player? we're a library.

**Comment by BartoszJarocki** [comment]
By "start the player" I mean trying to play video with your library.
Same with v2.4.0.rc1.

**Comment by itaykinnrot** [comment]
Fixed in our latest version - please make sure you're using player version 2.43+
